# Generated by Django 2.0.6 on 2018-06-12 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


from django.contrib.auth.models import User

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('komitets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('A', 'Admin'), ('RW', 'Read/Write'), ('R', 'Read'), ('B', 'Banned')], max_length=2)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komitets.Committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        # # WARNING Custom migration for unique email field in User model
        # migrations.AlterField(
        #     model_name=User,
        #     name='email',
        #     field=models.EmailField(unique=True)
        # ),

    ]
