# Generated by Django 2.0.6 on 2018-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komitets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='access_confirmation',
        ),
        migrations.AlterField(
            model_name='committee',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
