# Generated by Django 2.0.6 on 2018-06-18 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userprofile_user'),
        ('komitets', '0002_auto_20180615_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(through='users.UserPermissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committee',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
