# Generated by Django 2.0.6 on 2018-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komitets', '0003_auto_20180618_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='photo',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
