# Generated by Django 2.0.6 on 2018-06-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komitets', '0004_auto_20180618_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='photo',
        ),
        migrations.AddField(
            model_name='committee',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='committee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
