# Generated by Django 2.0.6 on 2018-06-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180620_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
