# Generated by Django 2.0.6 on 2018-06-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_answeroption_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('ANNOUNCE', 'Announcement'), ('PAY', 'Payment'), ('YNPOLL', 'Yes/No poll'), ('MAPOLL', 'Multi-answers poll'), ('MOPOLL', 'Multi-options poll')], max_length=15),
        ),
    ]
