# Generated by Django 2.0.6 on 2018-06-20 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0004_auto_20180620_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='answeroption',
            old_name='answer',
            new_name='answer_content',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.AnswerOption'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='answerers',
            field=models.ManyToManyField(through='cards.Answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
